Cancel scheduled newcomers
taskany-inc/crew pull request #1022
Opened 2024-08-07 10:23 UTC by nyet-ty

Resolve #1020

## PR includes

-   [x] Feature

2024-08-07 13:13 UTC, tsumo requested changes

2024-08-07 13:13 UTC, tsumo commented on src/components/HistoryRecord/HistoryRecord.i18n/ru.json
> +    "cancel request": "отменил(а) заявку"
canceled

2024-08-07 13:13 UTC, tsumo commented on src/utils/emailTemplates.ts
> +${tr('Cancelling planned newcommer {userName} to {organization}', { userName: name, organization })}
newcomer

2024-08-08 08:18 UTC, tsumo approved these changes

2024-08-08 12:36 UTC, asabotovich approved these changes

2024-08-08 13:07 UTC, merged