To decree form
taskany-inc/crew pull request #1157
Opened 2024-10-29 13:02 UTC by asabotovich

## PR includes

-   [x] Feature

## Related issues

2024-11-14 20:29 UTC, asabotovich commented
https://github.com/user-attachments/assets/4932d99f-e54a-4d86-8d49-36bd3a68f3f4

2024-11-15 12:03 UTC, tsumo requested changes

2024-11-15 12:03 UTC, tsumo commented on src/modules/userMethods.ts
> +        console.log('QQQ STATUS', updatedPositions);
log

2024-11-15 12:03 UTC, tsumo commented on src/pages/requests/users/decree/to/[userId].tsx
> +        try {
userEdit or userActiveStateEdit access check?

2024-11-15 12:21 UTC, tsumo approved these changes

2024-11-20 14:59 UTC, closed without merging