Request for scheduled employee exit in reading "read only"
taskany-inc/crew pull request #1167
Opened 2024-10-31 09:00 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

## Related issues

Resolve #1162

2024-11-07 08:27 UTC, tsumo requested changes

2024-11-07 08:27 UTC, tsumo commented on src/components/AddSupplementalPosition/AddSupplementalPosition.tsx
> +                    {nullable(readOnly, () => (
Show trigger on when readOnly?

2024-11-07 08:27 UTC, tsumo commented on src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx
> +    // @ts-ignore
ts ignore should not be used, what is the problem here?

2024-11-07 08:27 UTC, tsumo commented on src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx
> +        // @ts-ignore
no

2024-11-07 08:27 UTC, tsumo commented on src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx
> +                                    // @ts-ignore
no

2024-11-07 08:27 UTC, tsumo commented on src/hooks/useRouter.ts
> +    newInternalUserRequestReadOnly: (requestId: string) => `/requests/users/internal/${requestId}`,
just `internalUserRequest`, not `new`, because it's already created. And not `readOnly`, because it may depend on user access in the future

2024-11-07 08:27 UTC, tsumo commented on src/modules/userCreationRequestMethods.ts
> +    getRequestForEenternalEmployeeById: async (id: string) => {
typo `Eenternal`

2024-11-07 09:27 UTC, nyet-ty requested changes

2024-11-07 09:27 UTC, nyet-ty commented on src/components/AddSupplementalPosition/AddSupplementalPosition.tsx
> +                                    placeholder={readOnly ? tr('Not specified') : tr('Write percentage from 0.01 to 1')}
`tr('Not specified')` should be in value, not in placeholder

2024-11-07 09:27 UTC, nyet-ty commented on src/components/GroupComboBox/GroupComboBox.tsx
> +                    readOnly={readOnly}
this Input can't be visible, if SelectTrigger is readOnly

2024-11-07 09:27 UTC, nyet-ty commented on src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx
> +            workMode: userRequestQuery.data?.workMode,
add defaulValue for date

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormCommentsBlock/UserFormCommentsBlock.tsx
> +                            placeholder={readOnly ? tr('Not specified') : tr('Write some comments if needed')}
`tr('Not specified')` should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx
> +        login ? defaultValue : setValue('login', login);
why is it needed?

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx
> +                        placeholder={readOnly ? tr('Not specified') : tr('Write second name')}
tr('Not specified') should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx
> +                            placeholder={readOnly ? tr('Not specified') : 'name@mail.com'}
tr('Not specified') should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormPersonalDataBlock/UserFormPersonalDataBlock.tsx
> +                            placeholder={readOnly ? tr('Not specified') : 'email@example.com'}
tr('Not specified') should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx
> +                        placeholder={readOnly ? tr('Not specified') : tr('Write unit ID')}
tr('Not specified') should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx
> +                        placeholder={readOnly ? tr('Not specified') : tr('Write the percentage')}
tr('Not specified') should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormRegistrationBlock/UserFormRegistrationBlock.tsx
> +                                <SwitchControl disabled={readOnly} size="m" text={tr('Start')} value="start" />
is it necessary?

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.tsx
> +                            placeholder={readOnly ? tr('Not specified') : tr('Write equipment list')}
should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.tsx
> +                        placeholder={readOnly ? tr('Not specified') : tr('Write the application text')}
should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/components/UserFormWorkSpaceBlock/UserFormWorkSpaceBlock.tsx
> +                        placeholder={readOnly ? tr('Not specified') : tr('Write work mode comment')}
should be in value

2024-11-07 09:27 UTC, nyet-ty commented on src/modules/userCreationRequestSchemas.ts
> +export const userRequestInternalEmployeeSchema = z.object({
is new schema needed?

2024-11-07 09:27 UTC, nyet-ty commented on src/pages/requests/users/internal/[requestId]/index.tsx
> +        await ssg.userCreationRequest.getRequestForEnternalEmployeeById.fetch(stringIds.requestId);
here should be access check

2024-11-08 10:38 UTC, tsumo requested changes

2024-11-08 10:38 UTC, tsumo commented on src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.tsx
> +    console.log('defaultValues', defaultValues);
log

2024-11-08 10:38 UTC, tsumo commented on src/components/InternalUserCreationRequestPage/InternalUserCreationRequestPage.i18n/en.json
> +    "Request for a planned employee exit SD": ""
Request for a planned employee work start

2024-11-11 08:55 UTC, tsumo approved these changes

2024-11-11 10:03 UTC, nyet-ty approved these changes

2024-11-11 10:04 UTC, merged