feat(INTERNAL-1095): additional fields
taskany-inc/crew pull request #1213
Opened 2024-11-22 12:45 UTC by asabotovich

## PR includes

-   [x] Feature

## QA Instructions, Screenshots, Recordings

https://github.com/user-attachments/assets/ffc955bb-4584-4d4d-886d-d760579be6a2

2024-11-25 11:56 UTC, tsumo requested changes

2024-11-25 11:56 UTC, tsumo commented on src/modules/userCreationRequestMethods.ts
> +            ? await prisma.user.findUniqueOrThrow({ where: { id: data.buddyId ?? undefined } })
I think you don't need orThrow here

2024-11-25 11:56 UTC, tsumo commented on src/modules/userMethods.ts
> +        const currentOrgGrup = currentUser.memberships.find((m) => m.group.organizational);
typo

2024-11-26 10:26 UTC, nyet-ty requested changes

2024-11-26 16:59 UTC, nyet-ty approved these changes

2024-11-26 17:33 UTC, merged