User creation request scopes
taskany-inc/crew pull request #1231
Opened 2024-11-29 08:10 UTC by nyet-ty

2024-11-29 09:04 UTC, tsumo requested changes

2024-11-29 09:04 UTC, tsumo commented on prisma/schema.prisma
> +  readManyInternalUserRequest  Boolean @default(false)
requests

2024-11-29 09:04 UTC, tsumo commented on prisma/schema.prisma
> +  readManyExternalUserRequest  Boolean @default(false)
requests

2024-11-29 09:04 UTC, tsumo commented on prisma/schema.prisma
> +  readManyExternalFromMainUserRequest  Boolean @default(false)
same

2024-11-29 09:21 UTC, nyet-ty commented on src/components/PageHeader/PageHeader.tsx
> +            editExternalFromMainUserRequest: tr('editExternalFromMainUserRequest'),
Thanks!

2024-12-04 13:10 UTC, LamaEats approved these changes

2024-12-04 13:12 UTC, tsumo requested changes

2024-12-04 13:12 UTC, tsumo commented on src/trpc/router/userCreationRequestRouter.ts
> +const checkRequestTypeAccess = (type: string, forbidden: boolean) => {
`const checkRequestTypeAccess = (types: { type: string, forbidden: boolean }) => {}` would look cleaner

2024-12-12 09:41 UTC, merged