Add search by name
taskany-inc/crew pull request #1244
Opened 2024-12-03 15:17 UTC by Katrin-kudryash

## PR includes

-   [x] Feature

## Related issues

Resolve #1220

2024-12-04 08:51 UTC, Katrin-kudryash commented
https://github.com/user-attachments/assets/4ebebc90-c638-4dc6-a160-f96e5233c7f9

2024-12-04 12:41 UTC, tsumo requested changes

2024-12-04 12:41 UTC, tsumo commented on src/components/ProfilesManagementLayout/ProfilesManagementLayout.i18n/ru.json
> +    "Search in the table": ""
translation

2024-12-04 12:41 UTC, tsumo commented on src/components/ProfilesManagementSearch/ProfilesManagementSearch.tsx
> +export const ProfilesManagementSearch = () => {
Unused component

2024-12-04 13:26 UTC, asabotovich commented on src/modules/userTypes.ts
> +export interface UserFilterQueryd {
typo

2024-12-05 08:21 UTC, tsumo approved these changes

2024-12-05 08:45 UTC, nyet-ty approved these changes

2024-12-05 08:45 UTC, asabotovich approved these changes

2024-12-05 12:57 UTC, merged