Update decree form buttons
taskany-inc/crew pull request #1256
Opened 2024-12-10 12:25 UTC by asabotovich

## PR includes

-   [x] Bug Fix

2024-12-10 13:10 UTC, tsumo approved these changes

2024-12-12 07:55 UTC, nyet-ty requested changes

2024-12-12 07:55 UTC, nyet-ty commented on src/components/DecreeForm/DecreeForm.tsx
> +                                onDecide={router.accessCoordination}
do we decide on decrees?

2024-12-12 10:14 UTC, nyet-ty approved these changes

2024-12-12 10:15 UTC, merged