Default group from supervisor
taskany-inc/crew pull request #1265
Opened 2024-12-13 14:52 UTC by asabotovich

## PR includes

-   [x] Bug Fix
-   [x] Feature

2024-12-14 11:21 UTC, tsumo requested changes

2024-12-14 11:21 UTC, tsumo commented on src/components/UserFormTeamBlock/UserFormTeamBlock.tsx
> +    const { data: sepervisorGroups = [] } = trpc.group.getListByUserId.useQuery(
typo `sepervisorGroups`

2024-12-14 11:21 UTC, tsumo commented on src/components/UserFormTeamBlock/UserFormTeamBlock.tsx
> +    useEffect(() => {});
?

2024-12-16 10:25 UTC, nyet-ty requested changes

2024-12-16 10:25 UTC, nyet-ty commented on src/trpc/router/groupRouter.ts
> +        return groupMethods.getUserList(userId, rest);
this groups should be organizational

2024-12-16 12:17 UTC, nyet-ty approved these changes

2024-12-16 12:22 UTC, merged