Work and personal mails for user
taskany-inc/crew pull request #1287
Opened 2024-12-20 10:01 UTC by nyet-ty

## PR includes

-   [x] Feature

2024-12-20 11:36 UTC, tsumo requested changes

2024-12-20 11:36 UTC, tsumo commented on src/modules/serviceMethods.ts
> +        console.log('SERVICE_ID', data.serviceId);
log

2024-12-20 11:36 UTC, tsumo commented on src/modules/userMethods.ts
> +        console.log(request);
log

2024-12-20 11:36 UTC, tsumo commented on src/modules/userMethods.ts
> +            console.log(' if (request.personalEmail) {', emailService.name);
log

2024-12-20 11:36 UTC, tsumo commented on src/modules/userMethods.ts
> +            console.log('if (request.workEmail) {', emailService.name);
log

2024-12-23 11:11 UTC, tsumo approved these changes

2024-12-23 11:13 UTC, asabotovich approved these changes

2024-12-23 11:13 UTC, merged