Inline form in contacts
taskany-inc/crew pull request #175
Opened 2023-09-14 08:52 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

Resolve #31

2023-09-20 10:09 UTC, tsumo commented
Rebase please

2023-09-20 19:07 UTC, tsumo requested changes

2023-09-20 19:07 UTC, tsumo commented on src/components/ services/ServiceForm.tsx
> +    const onReset = () => {
Service id should also be reset here

2023-09-20 19:07 UTC, tsumo commented on src/components/ services/ServiceForm.tsx
> +export const ServiceForm: React.FC<ServicesFormProps> = ({ user }) => {
AddServiceToUserForm

2023-09-20 19:07 UTC, tsumo commented on src/components/users/UserContacts.tsx
> +            <ServiceForm user={user} />
We only need userId really, not the whole user

2023-09-20 19:07 UTC, tsumo commented on src/components/users/UserPage.tsx
> +
Unnecessary changes in this file

2023-09-20 19:07 UTC, tsumo commented on src/trpc/router/index.ts
> +    services: servicesRouter,
Singular form - `service: serviceRouter`

2023-09-20 19:07 UTC, tsumo commented on src/trpc/router/services-router.ts
> +export const servicesRouter = router({
`serviceRouter`

2023-09-21 10:14 UTC, tsumo requested changes

2023-09-21 10:14 UTC, tsumo commented on src/components/services/AddServiceToUserForm.tsx
> +    user?: User;
Don't need user

2023-09-21 12:54 UTC, tsumo approved these changes

2023-09-21 13:01 UTC, 9teen90nine approved these changes
cool

2023-09-21 13:01 UTC, merged