Get user services
taskany-inc/crew pull request #234
Opened 2023-10-10 08:58 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

## Related issues

Resolve #197

2023-10-10 17:42 UTC, tsumo requested changes

2023-10-10 17:42 UTC, tsumo commented on src/components/users/UserProfilePreview.tsx
> +                                <UserListItem user={user} />
This is wrong, supervisor is a different user

2023-10-10 17:42 UTC, tsumo commented on src/modules/service.schemas.ts
> +export const getUserServicesSchema = z.object({
Don't need a schema for one value, just use z.string() in procedure

2023-10-11 08:34 UTC, tsumo approved these changes

2023-10-11 08:42 UTC, 9teen90nine approved these changes

2023-10-11 08:43 UTC, merged