Remove services/projects/goals tab in group page
taskany-inc/crew pull request #251
Opened 2023-10-13 15:42 UTC by Katrin-kudryash

## PR includes

-   [ ] Bug Fix

## Related issues

Resolve #155

2023-10-14 13:34 UTC, tsumo requested changes

2023-10-14 13:34 UTC, tsumo commented on src/components/groups/TeamProfilePreview.tsx
> +                        {group.supervisor && (
Should use nullable

2023-10-14 13:34 UTC, tsumo commented on src/components/groups/TeamProfilePreview.tsx
> +                                {nullable(group.supervisor, (supervisor) => (
Unnecessary check

2023-10-14 15:22 UTC, tsumo commented on src/components/groups/TeamProfilePreview.tsx
> +                        {group.supervisor && (
This fix disappeared from the PR :)

2023-10-16 09:18 UTC, 9teen90nine commented on src/components/header/PageHeader.tsx
> +                    <UserMenu onClick={() => {}} email={session.data?.user.email} />
Should be either a TODO or a real action

2023-10-16 10:23 UTC, 9teen90nine approved these changes

2023-10-16 10:23 UTC, merged