Align all inline icons
taskany-inc/crew pull request #266
Opened 2023-10-16 17:47 UTC by tsumo

## PR includes

-   [x] Bug Fix
-   [x] Refactor

## Related issues

Resolve #254

2023-10-16 18:17 UTC, awinogradov requested changes

2023-10-16 18:17 UTC, awinogradov commented on src/components/InlineTrigger.tsx
> +const IconWrapper = styled.span`
U don't need it anymore

2023-10-16 18:17 UTC, awinogradov commented on src/components/MembershipGroupListItem.tsx
> +                {membership.roles.length > 0 && (
`nullable(membership.roles, () => {})`

2023-10-17 08:54 UTC, tsumo commented on src/components/MembershipGroupListItem.tsx
> +                {membership.roles.length > 0 && (
done

2023-10-17 09:20 UTC, 9teen90nine approved these changes

2023-10-17 10:01 UTC, merged