Device modal
taskany-inc/crew pull request #295
Opened 2023-10-26 15:25 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

## Related issues

Resolve #30

2023-10-27 07:29 UTC, tsumo requested changes

2023-10-27 07:29 UTC, tsumo commented on prisma/schema.prisma
> +  UserDevice UserDevice[]
Should be named `devices` and placed higher, with the other relations

2023-10-27 07:29 UTC, tsumo commented on src/components/AddDeviceToUserForm/AddDeviceToUserForm.i18n/ru.json
> +    "id": "",
Doesn't need translation

2023-10-27 07:29 UTC, tsumo commented on src/components/AddDeviceToUserForm/AddDeviceToUserForm.tsx
> +const StyledInput = styled(Input)`
Let's ask in chat, maybe if bricks already has an input styled like this

2023-10-30 08:58 UTC, 9teen90nine approved these changes

2023-10-31 08:14 UTC, tsumo requested changes

2023-10-31 08:14 UTC, tsumo commented on src/modules/modules.i18n/ru.json
> +    "Choose a device": ""
Needs translation

2023-10-31 08:53 UTC, tsumo approved these changes

2023-10-31 08:53 UTC, merged