New group interface on group page
taskany-inc/crew pull request #340
Opened 2023-11-13 12:12 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

## Related issues

Resolve #334

2023-11-13 12:16 UTC, tsumo requested changes
Please add fetch in getServerSideProps for proper ssg

2023-11-13 12:16 UTC, tsumo commented on prisma/seed.ts
> +    const sber = await prisma.group.create({
let's call this root

2023-11-14 07:49 UTC, tsumo commented on prisma/seed.ts
> +    const sber = await prisma.group.create({
or taskany

2023-11-14 08:35 UTC, tsumo approved these changes

2023-11-14 09:15 UTC, awinogradov requested changes

2023-11-14 12:40 UTC, tsumo approved these changes

2023-11-14 13:28 UTC, awinogradov approved these changes

2023-11-14 13:35 UTC, awinogradov approved these changes

2023-11-14 13:36 UTC, merged