Offline detector
taskany-inc/crew pull request #446
Opened 2024-01-31 07:41 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

## Related issues

Resolve #409

2024-01-31 08:36 UTC, nyet-ty approved these changes

2024-01-31 09:30 UTC, awinogradov requested changes

2024-01-31 09:30 UTC, awinogradov commented on src/components/OfflineBanner/OfflineBanner.tsx
> +    min-height: 40px;
`heigh: 40px`

2024-01-31 09:30 UTC, awinogradov commented on src/components/OfflineBanner/OfflineBanner.tsx
> +    padding-top: 10px;
use gap from `@taskany/colors`

2024-01-31 09:30 UTC, awinogradov commented on src/components/OfflineBanner/OfflineBanner.tsx
> +    background-color: #d24b4e;
use danger color from `@taskany/colors`

2024-01-31 09:35 UTC, tsumo requested changes

2024-01-31 09:35 UTC, tsumo commented on src/components/OfflineBanner/OfflineBanner.tsx
> +    return online ? null : <StyledBanner>{tr('You are currently offline. Check connection.')}</StyledBanner>;
nullable

2024-02-01 21:07 UTC, Katrin-kudryash commented
<img width="1353" alt="Untitled" src="https://github.com/taskany-inc/crew/assets/81121562/efb79902-b1b6-4912-97fe-af582258851b">

2024-02-01 21:23 UTC, awinogradov approved these changes

2024-02-02 08:14 UTC, tsumo approved these changes

2024-02-02 13:16 UTC, Katrin-kudryash commented
<img width="1358" alt="Untitled" src="https://github.com/taskany-inc/crew/assets/81121562/5760a546-68e6-46b6-9063-2741e6763048">

2024-02-02 13:17 UTC, 9teen90nine approved these changes

2024-02-05 10:27 UTC, awinogradov requested changes
![telegram-cloud-document-2-5326033289859842415](https://github.com/taskany-inc/crew/assets/982072/df8ad084-494b-4d0b-a778-2cfb6986e939)

2024-02-05 14:59 UTC, Katrin-kudryash commented
<img width="1572" alt="Untitled 3" src="https://github.com/taskany-inc/crew/assets/81121562/f9b9d1bd-3959-4507-9cf6-5dfb255ff644">

2024-02-05 16:05 UTC, Katrin-kudryash commented
<img width="1335" alt="Untitled 2" src="https://github.com/taskany-inc/crew/assets/81121562/45427840-5c93-48a6-b575-e797f92a2539">

2024-02-05 16:07 UTC, 9teen90nine commented on src/components/OfflineBanner/OfflineBanner.tsx
> +            </Text>{' '}
what's this?

2024-02-05 16:52 UTC, awinogradov approved these changes
@Katrin-kudryash @9teen90nine we need ticket to move this component to bricks and use everywhere

2024-02-05 16:54 UTC, merged

2024-02-05 17:00 UTC, 9teen90nine commented
> @Katrin-kudryash @9teen90nine we need ticket to move this component to bricks and use everywhere

https://github.com/taskany-inc/bricks/issues/806