Could not create a new role
taskany-inc/crew pull request #551
Opened 2024-02-26 17:28 UTC by Katrin-kudryash

## PR includes

-   [ ] Bug Fix

## Related issues

Resolve #527

2024-02-27 16:40 UTC, tsumo requested changes

2024-02-27 16:40 UTC, tsumo commented on src/components/RoleComboBox/RoleComboBox.i18n/ru.json
> +    "Add role": ""
translation

2024-02-27 16:40 UTC, tsumo commented on src/modules/modules.i18n/en.json
> +    "Only admins can create or add role": ""
roles

2024-02-27 16:40 UTC, tsumo commented on src/modules/roleSchemas.ts
> +export const createAndAddRoleToMembershipSchema = z
let's leave old schema name

2024-02-27 16:40 UTC, tsumo commented on src/trpc/router/roleRouter.ts
> +        accessCheck(groupAccess.isEditable(ctx.session.user));
why groupAccess?

2024-02-27 17:17 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/crew/assets/81121562/8e87d6b9-0fba-4103-98fd-bc1b547b092f

2024-02-27 19:33 UTC, tsumo approved these changes

2024-02-28 10:46 UTC, asabotovich commented on src/components/AddRoleToMembershipForm/AddRoleToMembershipForm.tsx
> +                text={{ name: search } ? 'Create' : ''}
It will be always `true`

2024-02-28 10:46 UTC, asabotovich commented on src/components/AddRoleToMembershipForm/AddRoleToMembershipForm.tsx
> +            await addToMembership({ membershipId, name: selectedRole.name, type: 'new' });
why don't you want just to check `id` inside `addToMembership`?

2024-02-28 10:46 UTC, asabotovich commented on src/components/AddRoleToMembershipForm/AddRoleToMembershipForm.tsx
> +                            {props.item.name}
`search ?` can be here

2024-02-28 10:49 UTC, asabotovich commented on src/components/AddRoleToMembershipForm/AddRoleToMembershipForm.tsx
> +                    search ? (
is it correct logic?

2024-02-28 23:05 UTC, Katrin-kudryash commented
https://github.com/taskany-inc/crew/assets/81121562/d88c2f1a-8903-4b21-9158-425bd55ca3a9

2024-02-28 23:44 UTC, asabotovich approved these changes

2024-02-28 23:44 UTC, asabotovich commented on src/components/AddRoleToMembershipForm/AddRoleToMembershipForm.tsx
> +                items={search ? [{ name: search }, ...(roleListQuery.data || [])] : roleListQuery.data}
Add access check

2024-02-28 23:45 UTC, asabotovich requested changes

2024-02-28 23:45 UTC, asabotovich commented on src/components/AddRoleToMembershipForm/AddRoleToMembershipForm.tsx
> +                items={search ? [{ name: search }, ...(roleListQuery.data || [])] : roleListQuery.data}
Add access check

2024-02-29 08:07 UTC, tsumo requested changes

2024-02-29 09:20 UTC, asabotovich approved these changes

2024-02-29 14:54 UTC, awinogradov approved these changes

2024-02-29 18:39 UTC, tsumo approved these changes

2024-02-29 18:41 UTC, merged