Allow vTeam creation to everyone
taskany-inc/crew pull request #620
Opened 2024-03-13 09:36 UTC by Katrin-kudryash

## PR includes

-   [ ] Feature

## Related issues

Resolve #613

2024-03-13 12:18 UTC, Katrin-kudryash commented
<img width="977" alt="Untitled" src="https://github.com/taskany-inc/crew/assets/81121562/cb02af79-8a4a-4a17-a123-ad9eb077680b">

2024-03-14 14:46 UTC, 9teen90nine commented on src/components/CreateGroupModal/CreateGroupModal.tsx
> +                    {data?.access.group.create && (
nullable

2024-03-14 15:47 UTC, tsumo requested changes

2024-03-14 16:12 UTC, 9teen90nine commented on src/components/CreateGroupModal/CreateGroupModal.tsx
> +                    {nullable(type !== 'virtual' && data?.access.group.create, () => (
if you extract `data.access.group.create` into a variable, there will be a copypaste elimination + the code will look much better

2024-03-14 16:12 UTC, 9teen90nine approved these changes

2024-03-14 16:16 UTC, tsumo requested changes

2024-03-14 16:16 UTC, tsumo commented on src/trpc/router/groupRouter.ts
> +            globalAccess.group.createVirtual();
where is accessCheck? Did you test this with different roles?

2024-03-14 16:46 UTC, merged