group.create method looses parentId
taskany-inc/crew pull request #637
Opened 2024-03-21 19:39 UTC by Katrin-kudryash

## PR includes

-   [ ] Bug Fix

## Related issues

Resolve #636

2024-03-21 20:14 UTC, tsumo requested changes

2024-03-21 20:14 UTC, tsumo requested changes

2024-03-21 20:14 UTC, tsumo commented on src/trpc/router/groupRouter.ts
> +    create: protectedProcedure.input(createGroupSchema).mutation(({ ctx, input }) => {
order doesn't matter in a destructured object

2024-03-21 20:49 UTC, tsumo approved these changes

2024-03-22 06:55 UTC, nyet-ty approved these changes

2024-03-22 07:09 UTC, merged