Add category information to an achievement
taskany-inc/crew pull request #701
Opened 2024-04-22 12:31 UTC by nyet-ty

Resolve #666 

## PR includes

-   [x] Feature

2024-04-22 12:56 UTC, tsumo requested changes

2024-04-22 12:56 UTC, tsumo commented on prisma/schema.prisma
> +  achievementCathegory String?
Category

2024-04-22 13:18 UTC, tsumo approved these changes

2024-04-24 07:56 UTC, 9teen90nine approved these changes

2024-04-24 07:57 UTC, merged