Add serviceNumber to external routes
taskany-inc/crew pull request #748
Opened 2024-05-07 14:21 UTC by DenisVorop

## PR includes

-   [x] Feature

## Related issues

Resolve #737

2024-05-08 12:00 UTC, tsumo requested changes

2024-05-08 12:00 UTC, tsumo commented on prisma/schema.prisma
> +  @@unique([organizationUnitId])
Only one service per organization?

2024-05-08 12:00 UTC, tsumo commented on prisma/schema.prisma
> +  userServices UserService[]
This should be one-to-one then

2024-05-08 12:00 UTC, tsumo commented on src/trpc/router/restRouter.ts
> +                await prisma.userService.create({
This will throw because there is no ExternalService with name 'ServiceNumber'

2024-05-13 13:02 UTC, 9teen90nine approved these changes

2024-05-13 13:04 UTC, merged