Create a new method for updating users
taskany-inc/crew pull request #758
Opened 2024-05-14 14:55 UTC by DenisVorop

## PR includes

-   [x] Refactor

## Related issues

Resolve #751

2024-05-15 08:09 UTC, tsumo requested changes

2024-05-15 08:09 UTC, tsumo commented on src/modules/userMethods.ts
> +    editUserFields: async (data: EditUserFields, user: User) => {
looks like its an extension of edit method with backwards compatibility, we can just reuse edit method with new fields in schema

2024-05-15 08:09 UTC, tsumo commented on src/modules/userMethods.ts
> +        if (data.supervisorId && data.supervisorId !== user.supervisorId) {
do we really need those checks for unchanged fields? they blow up the line count so much

2024-05-16 07:24 UTC, tsumo approved these changes

2024-05-16 13:42 UTC, nyet-ty requested changes

2024-05-16 13:42 UTC, nyet-ty commented on src/modules/userMethods.ts
> +        const newOrganization = await prisma.organizationUnit.findUnique({
Error should be thrown if no newOrganization would be found by data.organizationUnitId

2024-05-20 15:37 UTC, nyet-ty approved these changes

2024-05-20 15:38 UTC, merged