Planning for user account creation/blocking
taskany-inc/crew pull request #764
Opened 2024-05-16 11:31 UTC by nyet-ty

Resolve #700

## PR includes

-   [x] Feature

2024-05-22 13:14 UTC, tsumo requested changes

2024-05-22 13:14 UTC, tsumo commented on src/components/UserPage/UserPage.tsx
> +                    {nullable(sessionUser.role?.editScheduledDeactivation, () => (
`<Restricted />` is usually used for role-required actions

2024-05-22 14:31 UTC, nyet-ty commented on src/modules/userMethods.ts
> +                devices: { include: { device: true } },
on UserPage UserContacts and UserDevices loads services and devices, and NewScheduleDeactivationForm needs them too on same page. So I decided to get it with user and pass where it needed to be in props. And user methods getById and getByLogin used only on UserPage, UserPreview and UserSettings

2024-05-23 14:59 UTC, tsumo approved these changes

2024-05-23 14:59 UTC, tsumo commented on src/components/HistoryRecord/HistoryRecord.tsx
> +        const visible = useBoolean(false);
Update also ToggleShowMore to call onClick without arguments

2024-05-23 15:08 UTC, merged