feat: added the ability to change role access
taskany-inc/crew pull request #820
Opened 2024-05-29 09:17 UTC by DenisVorop

## PR includes

-   [x] Feature

## Related issues

Resolve #816 

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/crew/assets/95316053/7d5c11cd-ec90-443c-be5f-1bb6e67fefb8

https://github.com/taskany-inc/crew/assets/95316053/b24f148e-2070-4d20-ba6f-34e49287e322

2024-05-30 13:40 UTC, tsumo requested changes

2024-05-30 13:40 UTC, tsumo commented on src/modules/roleMethods.ts
>  export const roleMethods = {
we can rename this groupRoleMethods

2024-05-30 13:40 UTC, tsumo commented on src/modules/roleMethods.ts
> +    getListWithScope: (data: GetUserRoleWithScopeData) => {
and move this and other new code to userRoleMethods

2024-05-30 13:40 UTC, tsumo commented on src/modules/roleSchemas.ts
> +        field: z.enum([
we can do `z.string().refine((s) => scopes.includes(s))` to avoid copying all scopes

2024-05-30 13:40 UTC, tsumo commented on src/trpc/router/roleRouter.ts
> +        if (ctx.session.user.role?.code !== 'admin') {
Should be usual role check for scope `editRoleScopes`

2024-05-30 13:40 UTC, tsumo commented on src/trpc/router/userRouter.ts
> +        if (ctx.session.user.role?.code !== 'admin') {
role check for `editUserRole`

2024-05-30 13:40 UTC, tsumo commented on src/utils/notifications/notifications.i18n/en.json
> +    "Scope is changed": "",
Role is updated

2024-05-30 13:40 UTC, tsumo commented on src/utils/notifications/notifications.i18n/en.json
> +    "Changing scope...": "",
Updating role

2024-06-03 09:56 UTC, tsumo requested changes
Please, be careful with mixing group roles and user roles, they are absolutely not the same.

Also we need history records

2024-06-03 09:56 UTC, tsumo commented on src/components/UserPage/UserPage.tsx
> +                    <Restricted visible={sessionUser.role?.code === 'admin'}>
editUserRole

2024-06-03 09:56 UTC, tsumo commented on src/modules/roleHooks.ts
> +    const addScopeToRole = trpc.role.addScopeToRole.useMutation({
to userRoleHooks

2024-06-03 09:56 UTC, tsumo commented on src/modules/roleSchemas.ts
> +export const addScopeToRoleSchema = z.object({
to userRoleSchemas

2024-06-03 09:56 UTC, tsumo commented on src/trpc/router/roleRouter.ts
> +    getListWithScope: protectedProcedure.input(getUserRoleWithScopeSchema).query(({ input }) => {
to userRoleRouter

2024-06-03 09:56 UTC, tsumo commented on src/utils/access.ts
> +export const scopes: AccessOperation[] = objKeys({
This type won't show you an error if you forget one of the scopes.
I guess we need two variables to get type-safety: `scopesObj: Record<AccessOperation, true>` and then `scopes: AccessOperation[] = objKeys(...)`

2024-06-03 12:37 UTC, tsumo approved these changes

2024-06-03 12:57 UTC, asabotovich approved these changes

2024-06-03 13:03 UTC, merged