Attaches to s3 in crew
taskany-inc/crew pull request #839
Opened 2024-06-06 10:11 UTC by nyet-ty

Resolve #777 

## PR includes

-   [x] Feature

2024-06-06 12:38 UTC, tsumo commented on prisma/schema.prisma
> +model Attach {
empty line between models

2024-06-06 12:39 UTC, tsumo commented on src/hooks/useRouter.ts
> +    attach: (attachId: string) => `/api/attach/${attachId}`,
update useRouter below, please

2024-06-06 12:53 UTC, tsumo commented on src/modules/attachHandler.ts
> +    if (!file) throw new ErrorWithStatus(tr('No file finded'), 404);
found

2024-06-06 12:55 UTC, tsumo commented on src/modules/attachMethods.ts
> +    create,
lets move body of functions inside the object itself, this way it's one less click when you got from usage to definition in IDE

2024-06-06 12:57 UTC, tsumo commented on src/modules/attachModule.ts
> +export const attachModule = { remove };
why do we need this module?

2024-06-11 07:10 UTC, tsumo requested changes

2024-06-11 07:10 UTC, tsumo commented on src/pages/api/attach.ts
> +        const fileId = String(req.query.id);
Let's add history records for post and delete actions

2024-06-13 09:49 UTC, tsumo requested changes

2024-06-13 09:49 UTC, tsumo commented on src/utils/notifications/notificationsMap.ts
> +        attachDelete: {
I think this is `attachCreate`

2024-06-13 09:51 UTC, nyet-ty commented on src/utils/notifications/notificationsMap.ts
> +        attachDelete: {
it is, thanks

2024-06-13 10:30 UTC, asabotovich commented on src/modules/attachAccess.ts
> +    },
check editScheduledDeactivation and viewScheduledDeactivation flags in place

2024-06-13 10:30 UTC, asabotovich commented on src/pages/api/attach.ts
> +    })
keep handlers in one place?

2024-06-13 16:46 UTC, asabotovich approved these changes

2024-06-13 17:25 UTC, tsumo approved these changes

2024-06-13 17:28 UTC, merged