"Add team" button accessability
taskany-inc/crew pull request #854
Opened 2024-06-07 15:34 UTC by asabotovich

## PR includes

-   [x] Feature

## Related issues

Resolve #842 

## QA Instructions, Screenshots, Recordings

<img width="942" alt="Снимок экрана 2024-06-07 в 18 10 51" src="https://github.com/taskany-inc/crew/assets/9020793/1554b329-8586-43e0-922d-c8518ed290e5">
<img width="942" alt="Снимок экрана 2024-06-07 в 18 14 03" src="https://github.com/taskany-inc/crew/assets/9020793/b2d13254-3d74-4fa1-8fd8-2b479c0a84df">
<img width="942" alt="Снимок экрана 2024-06-07 в 18 14 21" src="https://github.com/taskany-inc/crew/assets/9020793/91a29798-d583-4784-890c-33d0e77c3b29">

2024-06-10 12:38 UTC, DenisVorop approved these changes

2024-06-10 15:25 UTC, asabotovich commented
https://github.com/taskany-inc/crew/assets/9020793/eab4806c-5516-46d4-b321-1de4955ed1e5

2024-06-11 07:00 UTC, tsumo requested changes

2024-06-13 11:24 UTC, asabotovich commented
https://github.com/taskany-inc/crew/assets/9020793/e82d06bf-91b8-4987-8eb9-5ab91bd5b59f

2024-06-13 11:30 UTC, tsumo approved these changes

2024-06-13 11:35 UTC, merged