Remove editAdministratedGroupTree flag
taskany-inc/crew pull request #855
Opened 2024-06-07 15:46 UTC by asabotovich

## PR includes

-   [x] Refactor
-   [x] Feature

## Related issues

Resolve #854 

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/crew/assets/9020793/65c299a2-6992-42a4-9f68-fe5fc85fab2c

2024-06-10 12:39 UTC, DenisVorop approved these changes

2024-06-11 07:04 UTC, tsumo requested changes

2024-06-11 07:04 UTC, tsumo commented on src/components/PageHeader/PageHeader.tsx
> -            editAdministratedGroupTree: tr('editing administrated teams'),
translations can be deleted as well

2024-06-11 07:04 UTC, tsumo commented on src/trpc/router/groupRouter.ts
> -        accessCheckAnyOf(
Probably should still check if new group is organizational

2024-06-13 12:51 UTC, tsumo approved these changes

2024-06-13 12:53 UTC, merged