Add an option to schedule new employee
taskany-inc/crew pull request #893
Opened 2024-06-20 12:31 UTC by nyet-ty

Resolve #863 

## PR includes

-   [x] Feature

2024-06-21 11:57 UTC, asabotovich requested changes

2024-06-21 11:57 UTC, asabotovich commented on src/modules/modules.i18n/ru.json
> +    "Planning new worker": "Пранируется выход сотрудника",
Пранируется

2024-06-21 11:57 UTC, asabotovich commented on src/modules/userMethods.ts
> +                ${tr('Planning new worker')} in ${getOrgUnitTitle(userCreationRequest.organization)}
In RU locale: `Пранируется выход сотрудника in ЦК Разработки Интерфейсов`

2024-06-21 11:57 UTC, asabotovich commented on src/modules/userMethods.ts
> +            </body>
May it better to keep markup templates separate from logic?

2024-06-26 07:55 UTC, tsumo approved these changes

2024-06-26 14:04 UTC, asabotovich approved these changes

2024-06-26 19:33 UTC, merged