Use url params for user list filter
taskany-inc/crew pull request #928
Opened 2024-07-01 15:30 UTC by IgorGoryany

## PR includes

-   [x] Feature

## Related issues

Resolve #897

2024-07-02 07:33 UTC, tsumo requested changes

2024-07-02 07:33 UTC, tsumo commented on src/components/UsersPage/UsersPage.tsx
> +        activeQuery: (values.activeQuery && values.activeQuery === 'true') as boolean | undefined,
replace type cast with honest ternary

2024-07-02 07:33 UTC, tsumo commented on src/hooks/useUserListFilterUrlParams.ts
> +            search: 'string',
Let's rename `getUserListSchema` fields by removing `Query` from them. This will make our urls look better

2024-07-02 13:52 UTC, tsumo approved these changes

2024-07-03 08:14 UTC, nyet-ty approved these changes

2024-07-03 09:10 UTC, merged