Don't send a meeting email when creating user with start date
taskany-inc/crew pull request #949
Opened 2024-07-05 08:34 UTC by nyet-ty

Resolve #943

2024-07-05 09:07 UTC, tsumo approved these changes

2024-07-05 13:53 UTC, tsumo requested changes

2024-07-05 13:53 UTC, tsumo commented on prisma/schema.prisma
> +  startDate DateTime?
workStartDate

2024-07-05 13:53 UTC, tsumo commented on src/modules/userMethods.ts
> +                startDate: acceptedRequest.date,
Should also be added to `(create / accept / decline)UserCreationRequest` event

2024-07-09 07:40 UTC, tsumo approved these changes

2024-07-09 13:53 UTC, 9teen90nine approved these changes

2024-07-09 13:54 UTC, merged