Scheduled jobs support
taskany-inc/crew pull request #952
Opened 2024-07-05 13:08 UTC by nyet-ty

Resolve #938

## PR includes

-   [x] Feature

2024-07-08 10:51 UTC, 9teen90nine approved these changes

2024-07-08 11:07 UTC, tsumo requested changes

2024-07-08 11:07 UTC, tsumo commented on src/utils/dateTime.ts
> +export const addHoursToDate = (date: Date, hours: number) => new Date(date.setHours(date.getHours() + hours));
why not `date.setUTCHours(23)`?

2024-07-09 07:39 UTC, tsumo approved these changes

2024-07-09 08:55 UTC, merged