feat: user preview in popup
taskany-inc/crew pull request #96
Opened 2023-08-10 09:40 UTC by Katrin-kudryash

Resolve #91

2023-08-11 13:41 UTC, awinogradov approved these changes

2023-08-18 16:36 UTC, 9teen90nine requested changes
No more api pages!

2023-08-18 16:36 UTC, 9teen90nine commented on src/components/users/UserTeams.tsx
> +                <InlineTrigger icon={<PlusIcon noWrap size="xs" />} text={'Add teams'} onClick={() => {}} />
todo comment

2023-08-18 16:36 UTC, 9teen90nine commented on src/pages/api/user/group/[groupId].ts
> +import type { NextApiRequest, NextApiResponse } from 'next';
no more API pages, use trpc backend

2023-08-21 08:31 UTC, Katrin-kudryash commented on src/pages/api/user/group/[groupId].ts
> +import type { NextApiRequest, NextApiResponse } from 'next';
ok, done

2023-08-21 08:33 UTC, 9teen90nine approved these changes

2023-08-21 08:34 UTC, merged