External user create request
taskany-inc/crew pull request #961
Opened 2024-07-14 13:16 UTC by tsumo

## PR includes

-   [x] Feature

## Related issues

Resolve #946 

## QA Instructions, Screenshots, Recordings

2024-07-14 20:24 UTC, nyet-ty requested changes

2024-07-14 20:24 UTC, nyet-ty commented on src/modules/userCreationRequestSchemas.ts
> +    supervisorId: z.string().nullish(),
we have supervisorLogin String in schema in model UserCreationRequest

2024-07-14 20:26 UTC, nyet-ty commented on src/modules/userCreationRequestSchemas.ts
> +    supervisorId: z.string().nullish(),
oh, my bad, it's ok

2024-07-15 07:42 UTC, nyet-ty commented on src/components/CreateUserModal/CreateUserModal.i18n/ru.json
> +    "Create request for user creation": "",
You forgot translations here

2024-07-15 07:57 UTC, tsumo commented on src/components/CreateUserModal/CreateUserModal.i18n/ru.json
> +    "Create request for user creation": "",
fixed

2024-07-15 07:58 UTC, nyet-ty approved these changes

2024-07-15 11:34 UTC, asabotovich approved these changes

2024-07-15 11:35 UTC, merged