Login should be unique in user requests
taskany-inc/crew pull request #978
Opened 2024-07-17 14:05 UTC by nyet-ty

Resolve #974 

## PR includes

-   [x] Bug Fix
-   [x] Feature

2024-07-17 18:15 UTC, tsumo requested changes
Check should be in createUserRequest method on back

2024-07-17 18:15 UTC, tsumo commented on src/modules/userMethods.ts
> +        const user = await prisma.user.findUnique({ where: { login } });
Can use count instead of find

2024-07-17 18:15 UTC, tsumo commented on src/components/CreateUserCreationRequestBaseForm/CreateUserCreationRequestBaseForm.tsx
> +                        (isLoginUnique.data === false ? { message: tr('User with login already exist') } : undefined)
Error should be set with setError, so that it stops form from submitting

2024-07-22 10:14 UTC, tsumo approved these changes

2024-07-22 15:06 UTC, asabotovich commented on src/components/CreateUserCreationRequestInternalEmployeeForm/CreateUserCreationRequestInternalEmployeeForm.tsx
> +        } else clearErrors('login');
the same

2024-07-22 15:45 UTC, asabotovich approved these changes

2024-07-22 15:49 UTC, merged