Add author to the mailing list when scheduling new user
taskany-inc/crew pull request #995
Opened 2024-07-22 08:37 UTC by nyet-ty

Resolve #985 

## PR includes

-   [x] Feature

2024-07-22 09:38 UTC, tsumo requested changes

2024-07-22 09:38 UTC, tsumo commented on prisma/schema.prisma
> +  userCreationReauestCreator     UserCreationRequest[] @relation("userCreationReauestCreator")
typo Reauest

2024-07-22 09:38 UTC, tsumo commented on src/modules/userMethods.ts
> +        user && !users.some(({ email }) => email === user.email) && users.push({ email: user.email, name: user.name! });
condition is getting long, let's rewrite statement to `if`

2024-07-22 16:08 UTC, asabotovich commented on src/config.ts
> +    sectionAmountForAchievement: process.env.SECTION_AMOUNT_FOR_ACHIEVEMENT || 5,
Fix me, pls

2024-07-22 20:04 UTC, asabotovich approved these changes

2024-07-23 07:05 UTC, tsumo approved these changes

2024-07-23 07:09 UTC, merged